#!/bin/sh -e

export DESTDIR="$1"

sed -i 's/float t[6];/float t[6] = {0}/g' 3rd-party/nanosvg/src/nanosvg.h

meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Djpeg=enabled \
    -Dpng=enabled \
    output

ninja -C output
ninja -C output install
