#!/bin/sh -e

export DESTDIR="$1"

if [ "$(uname -m)" == "i686" ]; then
    sed -e "/^#elif defined(Q_CC_GNU_ONLY)/s/.*/& \&\& 0/" \
        -i qtbase/src/corelib/global/qtypes.h
fi

./configure --prefix=/usr

ninja
ninja install

# install sudoers file to preserve env
mkdir -p $DESTDIR/etc/sudoers.d/
cp qt $DESTDIR/etc/sudoers.d/

# install profile file for qt6 exports
mkdir -p $DESTDIR/etc/profile.d/
cp qt6.sh $DESTDIR/etc/profile.d/
