#!/bin/sh -e

DESTDIR="$1"

INSTALLDIR=$DESTDIR/etc/profile.d
mkdir -p $INSTALLDIR
cp kf6.sh $INSTALLDIR
cp qt6.sh $INSTALLDIR

# install sudoers file to preserve env
mkdir -p $DESTDIR/etc/sudoers.d/
cp qt $DESTDIR/etc/sudoers.d/

